FROM nginx:stable

# Install git
RUN apt-get update && apt-get install -y git

# Link workspace source to nginx
#RUN rm -rf /usr/share/nginx/html && \
#    ln -s /workspaces/jademalo.github.io /usr/share/nginx/html